AssertionError      断言语句(assert)失败
AttributeError      尝试访问未知的对象属性
IndexError          索引超出序列的范围
KeyError            字典中查找一个不存在的关键字
NameError           尝试访问一个不存在的变量
OSError             操作系统产生的异常（例如打开一个不存在的文件）
OverflowError       数值运算超出最大限制
SyntaxError         Python语法错误
ZeroDivisionError   除数为零
IndentationError    缩进错误
